services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=moviesplay_db'
      - 'POSTGRES_PASSWORD=sebastian_dev'
      - 'POSTGRES_USER=sebastian'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata: